name: Beta Release

on:
  push:
    branches: [beta]
  workflow_dispatch:

jobs:
  release:
    uses: ConductionNL/.github/.github/workflows/release-beta.yml@main
    with:
      app-name: openbuild
    secrets: inherit
