name: Stable Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: ConductionNL/.github/.github/workflows/release-stable.yml@main
    with:
      app-name: openbuild
    secrets: inherit
